import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Link from 'next/link'
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const dana = localFont({
  src: [
    {
      path: "../assets/fonts/dana-fanum-regular.ttf",
    }
  ]
})


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token");
  return (
    <html lang="en">
      <body
        className={` min-h-screen flex flex-row justify-center ${dana.className}`}
      >
      <header className="fixed top-0 z-50 w-3xl bg-gray-100 shadow-md rounded-3xl m-5 hover:shadow-2xl transition-shadow duration-300">
        <nav className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between h-14">
          <Link href="/dashboard" className="text-lg font-semibold text-gray-800 hover:text-blue-500 hover:duration-400">داشبورد</Link>
          <div className="flex flex-row-reverse items-center space-x-4 space-x-reverse">
            {!token ? <Link
              href="/login"
              className=" hover:text-blue-500 hover:duration-400 text-gray-600 hover:scale-120 hover:bg-blue-50 px-2 py-1 rounded-md text-sm font-medium transition-colors duration-200"
            >
             لاگین
            </Link> : ""}
            <Link
              href="/"
              className=" hover:text-blue-500 hover:duration-400 text-gray-600 hover:scale-120 hover:bg-blue-50 px-2 py-1 rounded-md text-sm font-medium transition-colors duration-200"
            >
              خانه
            </Link>
          </div>
        </nav>
      </header>
        {children}
      </body>
    </html>
  );
}
